### ISSUE TITLE
使用github最新版的问题

### ISSUE THREAD

**Issue by CyberTNT** [ASTWY/nonebot_plugin_bilibili_viode#5]
使用github最新版后，由于utils.py中的函数都添加了raise错误的行为，导致main.py中的逻辑无法继续运行，所有的关键字都会报错无法显示出效果

**Comment by ASTWY** [comment]
请使用pypi发布的版本，github的版本并没有完全更新，我正在重写一个可自定义模板

**Comment by zhulinyv** [comment]
pypi 上的 1.0.1 存在同样问题。
