### ISSUE TITLE
能否添加对短链接的支持？

### ISSUE THREAD

**Issue by IsaacTheMouse** [ASTWY/nonebot_plugin_bilibili_viode#6]
有部分群友习惯使用的分享功能，复制出来的链接是b23.tv域名，能否添加对该域名的识别？

**Comment by ASTWY** [comment]
在项目中是有对b23.tv等短连接的支持，如果出现bug情况，请提供一下未识别的短连接

**Comment by IsaacTheMouse** [comment]
我bot突然特大喜报了……所以暂时估计没法提供log了，十分抱歉。

**Comment by IsaacTheMouse** [comment]
找到问题了，是因为发送的消息不以链接开始。
![_POC0C3%56RXYF64Q00UWNJ](https://github.com/ASTWY/nonebot_plugin_bilibili_viode/assets/49868138/bdad941c-bd7c-4855-9ba7-1d3977add056)

**Comment by ASTWY** [comment]
[v1.0.1](https://github.com/ASTWY/nonebot_plugin_bilibili_viode/releases/tag/v1.0.1)已修复，请安装最新发布版本
